"""Add TokenRefreshers table

Revision ID: 2cf2e7a3b12f
Revises: c9ddcdcf0b2d
Create Date: 2024-01-19 12:46:44.427934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf2e7a3b12f'
down_revision = 'c9ddcdcf0b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gc_token_refreshers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('refresh_token', sa.String(length=36), nullable=False),
    sa.Column('expire', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gc_token_refreshers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gc_token_refreshers_refresh_token'), ['refresh_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_gc_token_refreshers_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gc_token_refreshers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gc_token_refreshers_username'))
        batch_op.drop_index(batch_op.f('ix_gc_token_refreshers_refresh_token'))

    op.drop_table('gc_token_refreshers')
    # ### end Alembic commands ###
