"""Initial database

Revision ID: 308fc4ae3f90
Revises: 
Create Date: 2024-03-29 01:15:11.980400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308fc4ae3f90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('update_date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('docs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_docs_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_docs_update_date'), ['update_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_docs_username'), ['username'], unique=False)

    op.create_table('page_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_folders_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_folders_parent'), ['parent'], unique=False)

    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('folder', sa.Integer(), nullable=False),
    sa.Column('page_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pages_folder'), ['folder'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_page_type'), ['page_type'], unique=False)

    op.create_table('token_refreshers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('refresh_token', sa.String(length=36), nullable=False),
    sa.Column('expire', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_refreshers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_refreshers_expire'), ['expire'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_refreshers_refresh_token'), ['refresh_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_refreshers_username'), ['username'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('passwd', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('intro_text', sa.Text(), nullable=True),
    sa.Column('signdate', sa.Integer(), nullable=False),
    sa.Column('confirm', sa.Integer(), nullable=False),
    sa.Column('confirm_key', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_confirm_key'), ['confirm_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_confirm_key'))

    op.drop_table('users')
    with op.batch_alter_table('token_refreshers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_refreshers_username'))
        batch_op.drop_index(batch_op.f('ix_token_refreshers_refresh_token'))
        batch_op.drop_index(batch_op.f('ix_token_refreshers_expire'))

    op.drop_table('token_refreshers')
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_page_type'))
        batch_op.drop_index(batch_op.f('ix_pages_name'))
        batch_op.drop_index(batch_op.f('ix_pages_folder'))

    op.drop_table('pages')
    with op.batch_alter_table('page_folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_folders_parent'))
        batch_op.drop_index(batch_op.f('ix_page_folders_name'))

    op.drop_table('page_folders')
    with op.batch_alter_table('docs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_docs_username'))
        batch_op.drop_index(batch_op.f('ix_docs_update_date'))
        batch_op.drop_index(batch_op.f('ix_docs_date'))

    op.drop_table('docs')
    # ### end Alembic commands ###
