"""unique refresh_token

Revision ID: 50ec56c01479
Revises: 9d0c5c629bfa
Create Date: 2024-05-06 06:08:34.416667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ec56c01479'
down_revision: Union[str, None] = '9d0c5c629bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_refreshers_refresh_token', table_name='token_refreshers')
    op.create_index(op.f('ix_token_refreshers_refresh_token'), 'token_refreshers', ['refresh_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_refreshers_refresh_token'), table_name='token_refreshers')
    op.create_index('ix_token_refreshers_refresh_token', 'token_refreshers', ['refresh_token'], unique=False)
    # ### end Alembic commands ###
