"""Add indexes to tables

Revision ID: 61c019615353
Revises: 2cf2e7a3b12f
Create Date: 2024-01-19 12:50:02.379862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c019615353'
down_revision = '2cf2e7a3b12f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gc_token_refreshers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gc_token_refreshers_expire'), ['expire'], unique=False)

    with op.batch_alter_table('gc_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gc_users_confirm_key'), ['confirm_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gc_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gc_users_confirm_key'))

    with op.batch_alter_table('gc_token_refreshers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gc_token_refreshers_expire'))

    # ### end Alembic commands ###
