"""Add pages and page_folders

Revision ID: 8972e10e3ce6
Revises: 61c019615353
Create Date: 2024-03-28 01:38:45.355521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8972e10e3ce6'
down_revision = '61c019615353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gc_page_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gc_page_folders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gc_page_folders_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_gc_page_folders_parent'), ['parent'], unique=False)

    op.create_table('gc_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('folder', sa.Integer(), nullable=False),
    sa.Column('page_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gc_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gc_pages_folder'), ['folder'], unique=False)
        batch_op.create_index(batch_op.f('ix_gc_pages_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_gc_pages_page_type'), ['page_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gc_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gc_pages_page_type'))
        batch_op.drop_index(batch_op.f('ix_gc_pages_name'))
        batch_op.drop_index(batch_op.f('ix_gc_pages_folder'))

    op.drop_table('gc_pages')
    with op.batch_alter_table('gc_page_folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gc_page_folders_parent'))
        batch_op.drop_index(batch_op.f('ix_gc_page_folders_name'))

    op.drop_table('gc_page_folders')
    # ### end Alembic commands ###
