"""Add tables

Revision ID: 9d0c5c629bfa
Revises: 308fc4ae3f90
Create Date: 2024-05-06 07:03:06.778228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0c5c629bfa'
down_revision: Union[str, None] = '308fc4ae3f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('autoincrement', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tables_autoincrement'), ['autoincrement'], unique=False)
        batch_op.create_index(batch_op.f('ix_tables_name'), ['name'], unique=False)

    op.create_table('table_columns',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('column_type', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('table_columns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_columns_column_type'), ['column_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_columns_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_columns_table_id'), ['table_id'], unique=False)

    op.create_table('table_rows',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('table_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_rows_table_id'), ['table_id'], unique=False)

    op.create_table('table_values',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('row_id', sa.BigInteger(), nullable=False),
    sa.Column('column_id', sa.BigInteger(), nullable=False),
    sa.Column('val_str', sa.String(length=191), nullable=True),
    sa.Column('val_int', sa.BigInteger(), nullable=True),
    sa.Column('val_bool', sa.Boolean(), nullable=True),
    sa.Column('val_decimal', sa.Numeric(), nullable=True),
    sa.Column('val_float', sa.Float(), nullable=True),
    sa.Column('val_double', sa.Double(), nullable=True),
    sa.Column('val_text', sa.Text(), nullable=True),
    sa.Column('val_binpath', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['column_id'], ['table_columns.id'], ),
    sa.ForeignKeyConstraint(['row_id'], ['table_rows.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('table_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_table_values_column_id'), ['column_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_values_row_id'), ['row_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_values_table_id'), ['table_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_values_val_binpath'), ['val_binpath'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_values_val_bool'), ['val_bool'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_values_val_decimal'), ['val_decimal'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_values_val_double'), ['val_double'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_values_val_float'), ['val_float'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_values_val_int'), ['val_int'], unique=False)
        batch_op.create_index(batch_op.f('ix_table_values_val_str'), ['val_str'], unique=False)

    with op.batch_alter_table('docs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('page_folders', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_id', sa.BigInteger(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_index('ix_pages_folder')
        batch_op.create_index(batch_op.f('ix_pages_folder_id'), ['folder_id'], unique=False)
        batch_op.drop_column('folder')

    with op.batch_alter_table('token_refreshers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('token_refreshers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder', sa.INTEGER(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_pages_folder_id'))
        batch_op.create_index('ix_pages_folder', ['folder'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('folder_id')

    with op.batch_alter_table('page_folders', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('docs', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('table_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_values_val_str'))
        batch_op.drop_index(batch_op.f('ix_table_values_val_int'))
        batch_op.drop_index(batch_op.f('ix_table_values_val_float'))
        batch_op.drop_index(batch_op.f('ix_table_values_val_double'))
        batch_op.drop_index(batch_op.f('ix_table_values_val_decimal'))
        batch_op.drop_index(batch_op.f('ix_table_values_val_bool'))
        batch_op.drop_index(batch_op.f('ix_table_values_val_binpath'))
        batch_op.drop_index(batch_op.f('ix_table_values_table_id'))
        batch_op.drop_index(batch_op.f('ix_table_values_row_id'))
        batch_op.drop_index(batch_op.f('ix_table_values_column_id'))

    op.drop_table('table_values')
    with op.batch_alter_table('table_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_rows_table_id'))

    op.drop_table('table_rows')
    with op.batch_alter_table('table_columns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_table_columns_table_id'))
        batch_op.drop_index(batch_op.f('ix_table_columns_name'))
        batch_op.drop_index(batch_op.f('ix_table_columns_column_type'))

    op.drop_table('table_columns')
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tables_name'))
        batch_op.drop_index(batch_op.f('ix_tables_autoincrement'))

    op.drop_table('tables')
    # ### end Alembic commands ###
