"""add uuid column

Revision ID: dd23061f0fd7
Revises: 32f6794f60da
Create Date: 2025-06-25 14:24:29.900719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd23061f0fd7'
down_revision: Union[str, None] = '32f6794f60da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_docs_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('page_folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_page_folders_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_pages_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_uuid'))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('page_folders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_folders_uuid'))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('docs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_docs_uuid'))
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
